# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'etkinlikliste.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(339, 413)
        self.katilimciTable = QtWidgets.QTableWidget(Form)
        self.katilimciTable.setGeometry(QtCore.QRect(0, 60, 341, 351))
        self.katilimciTable.setObjectName("katilimciTable")
        self.katilimciTable.setColumnCount(3)
        self.katilimciTable.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.katilimciTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.katilimciTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.katilimciTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.katilimciTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.katilimciTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.katilimciTable.setHorizontalHeaderItem(2, item)
        self.etkinlikBox = QtWidgets.QComboBox(Form)
        self.etkinlikBox.setGeometry(QtCore.QRect(90, 20, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.etkinlikBox.setFont(font)
        self.etkinlikBox.setObjectName("etkinlikBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 39))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Etkinlik Listesi"))
        item = self.katilimciTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Ad"))
        item = self.katilimciTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Soyad"))
        item = self.katilimciTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Telefon"))
        self.label.setText(_translate("Form", "Etkinlik:"))
