# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iptal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(252, 142)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 211, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.etkinlikBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.etkinlikBox.setFont(font)
        self.etkinlikBox.setObjectName("etkinlikBox")
        self.verticalLayout.addWidget(self.etkinlikBox)
        self.iptalButon = QtWidgets.QPushButton(Form)
        self.iptalButon.setGeometry(QtCore.QRect(130, 100, 101, 27))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.iptalButon.setFont(font)
        self.iptalButon.setObjectName("iptalButon")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "İptal Et"))
        self.label.setText(_translate("Form", "Etkinlikler"))
        self.iptalButon.setText(_translate("Form", "İptal Et"))
